steps:

# Build the Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/gcpcicdimages','.']

# Push the Docker Image to GCR
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/gcpcicdimages']

# Deploy Container Image to GKE
- name: 'gcr.io/cloud-builders/gke-deploy'
  args: 
  - run
  - --filename=kubernetes/deployment.yaml
  - --image=gcr.io/$PROJECT_ID/gcpcicdimages
  - --location=us-central1-c
  - --cluster=awaden-gke
  - --namespace=default